spring.application.name=campuscrush
server.port=${PORT:8080}
server.error.include-message=never

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

brevo.api-key=${BREVO_API_KEY}
brevo.from-email=${BREVO_FROM_EMAIL}

jwt.secret=${JWT_SECRET}